// apps/finance/src/components/settings/SettingsSection.tsx
import type { ReactNode } from "react";

export function SettingsSection({
  title,
  desc,
  testId,
  children,
}: {
  title: string;
  desc?: string;
  testId?: string;
  children: ReactNode;
}) {
  return (
    <div className="card settings-section" data-testid={testId}>
      <h3>{title}</h3>
      {desc ? <p className="muted-note">{desc}</p> : null}
      {children}
    </div>
  );
}

// apps/fitness/src/lib/components/settings/SettingsSection.svelte
<script>
  /** @type {{ title: string, desc?: string, testId?: string, children }} */
  let { title, desc = '', testId = '', children } = $props();
</script>

<div class="settings-block set-group" data-testid={testId || undefined}>
  <h3 class="block-title sg-title">{title}</h3>
  {#if desc}
    <p class="block-desc">{desc}</p>
  {/if}
  {@render children?.()}
</div>
