// apps/finance/src/components/stocks/HoldingsOverviewCard.tsx
import { useMemo } from "react";
import type { FinanceData } from "../../types";
import {
  buildPositionRows,
  sortPositionRows,
  sortedSnapshots,
  snapshotAsOfLabel,
} from "../../engine/holdingsPortfolio";
import { useHoldingsLive } from "../../hooks/useHoldingsLive";
import type { LiveTrackStatus } from "../../hooks/useHoldingsLive";
import { money, signedMoney, depositDeltaClass } from "../../format";
import { InstitutionLogo } from "../InstitutionLogo";
import { quoteSafeToSpend } from "../../copy/terminology";
import { useLocale } from "../../i18n/context";

function liveStatusShort(t: (key: string) => string, status: LiveTrackStatus): string {
  return t(`stocks.liveStatus.short.${status}`);
}

export function HoldingsOverviewCard({
  data,
  tabActive,
  onGoStocks,
}: {
  data: FinanceData;
  tabActive: boolean;
  onGoStocks: (snapshotId?: string) => void;
}) {
  const { t } = useLocale();
  const snapshots = sortedSnapshots(data.holdingsSnapshots);
  const latest = snapshots[0];
  const symbols = useMemo(
    () => latest?.positions.map((p) => p.ticker) ?? [],
    [latest?.id, latest?.positions]
  );

  const live = useHoldingsLive(symbols, Boolean(latest), tabActive);

  const liveTotal = useMemo(() => {
    if (!latest) return null;
    const rows = buildPositionRows(latest, live.quotes);
    return rows.reduce((sum, r) => sum + r.liveValue, 0);
  }, [latest, live.quotes]);

  const topReturners = useMemo(() => {
    if (!latest) return [];
    const rows = sortPositionRows(buildPositionRows(latest, live.quotes), "return-desc");
    return rows.filter((r) => (r.position.totalReturnAmount ?? 0) !== 0).slice(0, 3);
  }, [latest, live.quotes]);

  if (!latest) return null;

  return (
    <div className="card holdings-overview-card">
      <div className="section-head">
        <h3 className="flex-row">
          <InstitutionLogo name="Robinhood" size="sm" />
          {t("stocks.overview.title")}
        </h3>
        <button type="button" className="btn outline compact" onClick={() => onGoStocks(latest.id)}>
          {t("stocks.overview.openAllocation")}
        </button>
      </div>
      <p className="muted-note">
        {t("stocks.overview.marketValueNote", { safeToSpend: quoteSafeToSpend() })}
      </p>
      <div className="list">
        <div className="kv">
          <span className="k">{t("stocks.overview.portfolioMarketValue")}</span>
          <span>{money(liveTotal ?? latest.holdingsMarketValue, data.privacy)}</span>
        </div>
        {latest.impliedCostBasis != null && (
          <div className="kv">
            <span className="k">{t("stocks.overview.totalCost")}</span>
            <span>{money(latest.impliedCostBasis, data.privacy)}</span>
          </div>
        )}
        {latest.unrealizedGain != null && (
          <div className="kv">
            <span className="k">{t("stocks.overview.cumulativePnL")}</span>
            <span className={depositDeltaClass(latest.unrealizedGain)}>
              {signedMoney(latest.unrealizedGain, data.privacy)}
              {latest.weightedTotalReturnPct != null && (
                <span className="text-secondary inline-meta-tight">
                  {latest.weightedTotalReturnPct >= 0 ? "+" : ""}
                  {latest.weightedTotalReturnPct.toFixed(2)}%
                </span>
              )}
            </span>
          </div>
        )}
        {latest.todayReturnPctApprox != null && (
          <div className="kv">
            <span className="k">{t("stocks.overview.todayPnL")}</span>
            <span className={depositDeltaClass(latest.todayReturnPctApprox)}>
              {latest.todayReturnAmountApprox != null
                ? signedMoney(latest.todayReturnAmountApprox, data.privacy)
                : ""}
              {latest.todayReturnAmountApprox != null ? " · " : ""}
              {latest.todayReturnPctApprox >= 0 ? "+" : ""}
              {latest.todayReturnPctApprox.toFixed(2)}%
            </span>
          </div>
        )}
        <div className="kv">
          <span className="k">{t("stocks.overview.dataAsOf")}</span>
          <span>{snapshotAsOfLabel(latest)}</span>
        </div>
        <div className="kv">
          <span className="k">{t("stocks.overview.quoteStatus")}</span>
          <span className="holdings-overview-live-meta">
            <span className={`dot ${live.status === "live" ? "ok" : live.status === "error" ? "critical" : "warn"}`} />
            {liveStatusShort(t, live.status)}
            {tabActive ? "" : t("stocks.overview.pausedWhenInactive")}
          </span>
        </div>
        <div className="kv">
          <span className="k">{t("stocks.overview.positionCount")}</span>
          <span>{latest.positionCount}</span>
        </div>
      </div>
      {topReturners.length > 0 && (
        <div className="holdings-overview-movers">
          <span className="label">{t("stocks.overview.topReturners")}</span>
          <ul>
            {topReturners.map((row) => (
              <li key={row.position.id}>
                <span className="holdings-overview-mover-ticker">{row.position.ticker}</span>
                <span className={depositDeltaClass(row.position.totalReturnAmount ?? 0)}>
                  {signedMoney(row.position.totalReturnAmount ?? 0, data.privacy)}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

// apps/finance/src/lib/components/stocks/HoldingsOverviewCard.svelte
<script>
  import { onMount } from 'svelte'
  import {
    buildPositionRows,
    sortPositionRows,
    sortedSnapshots,
    snapshotAsOfLabel,
  } from '$lib/engine/holdingsPortfolio'
  import { fetchLiveQuotes } from '$lib/quotes'
  import { money, signedMoney, depositDeltaClass } from '$lib/format.js'
  import InstitutionLogo from '$lib/components/InstitutionLogo.svelte'
  import { quoteSafeToSpend } from '@life-os/finance-core/copy/terminology'
  import { t } from '$lib/i18n.svelte.js'

  /** @typedef {import('../../types.js').FinanceData} FinanceData */
  /** @typedef {'idle' | 'loading' | 'live' | 'partial' | 'stale' | 'error' | 'paused'} LiveTrackStatus */

  /** @type {{ data: FinanceData, tabActive: boolean, onGoStocks: (snapshotId?: string) => void }} */
  let { data, tabActive, onGoStocks } = $props()

  const snapshots = $derived(sortedSnapshots(data.holdingsSnapshots))
  const latest = $derived(snapshots[0])
  const symbols = $derived(latest?.positions.map((p) => p.ticker) ?? [])

  /** @type {Record<string, import('$lib/quotes').LiveQuote>} */
  let quotes = $state({})
  /** @type {LiveTrackStatus} */
  let status = $state('idle')

  const normalizedSymbols = $derived(
    [...new Set(symbols.map((s) => s.trim().toUpperCase()).filter(Boolean))],
  )

  const liveTotal = $derived.by(() => {
    if (!latest) return null
    const rows = buildPositionRows(latest, quotes)
    return rows.reduce((sum, r) => sum + r.liveValue, 0)
  })

  const topReturners = $derived.by(() => {
    if (!latest) return []
    const rows = sortPositionRows(buildPositionRows(latest, quotes), 'return-desc')
    return rows.filter((r) => (r.position.totalReturnAmount ?? 0) !== 0).slice(0, 3)
  })

  const displayStatus = $derived(
    !latest || !tabActive
      ? 'paused'
      : normalizedSymbols.length === 0
        ? 'idle'
        : status,
  )

  /** @param {LiveTrackStatus} s */
  function liveStatusShort(s) {
    return t(`stocks.liveStatus.short.${s}`)
  }

  async function refresh() {
    const uniq = normalizedSymbols
    if (uniq.length === 0) {
      status = 'idle'
      return
    }
    status = 'loading'
    try {
      const next = await fetchLiveQuotes(uniq)
      const got = Object.keys(next).length
      const hasCachedQuotes = Object.keys(quotes).length > 0
      if (got === 0) {
        status = hasCachedQuotes ? 'stale' : 'error'
        return
      }
      quotes = { ...quotes, ...next }
      status = got < uniq.length ? 'partial' : 'live'
    } catch {
      status = Object.keys(quotes).length > 0 ? 'stale' : 'error'
    }
  }

  onMount(() => {
    let timer = null
    const run = () => {
      if (!latest || !tabActive || document.visibilityState === 'hidden') return
      void refresh()
    }
    run()
    timer = setInterval(run, normalizedSymbols.length <= 8 ? 15_000 : 30_000)
    const onVisible = () => {
      if (document.visibilityState === 'visible' && tabActive) void refresh()
    }
    document.addEventListener('visibilitychange', onVisible)
    return () => {
      if (timer) clearInterval(timer)
      document.removeEventListener('visibilitychange', onVisible)
    }
  })

  $effect(() => {
    if (!latest || !tabActive) return
    void refresh()
  })
</script>

{#if latest}
  <div class="card holdings-overview-card">
    <div class="section-head">
      <h3 class="flex-row">
        <InstitutionLogo name="Robinhood" size="sm" />
        {t('stocks.overview.title')}
      </h3>
      <button type="button" class="btn outline compact" onclick={() => onGoStocks(latest.id)}>
        {t('stocks.overview.openAllocation')}
      </button>
    </div>
    <p class="muted-note">
      {t('stocks.overview.marketValueNote', { safeToSpend: quoteSafeToSpend() })}
    </p>
    <div class="list">
      <div class="kv">
        <span class="k">{t('stocks.overview.portfolioMarketValue')}</span>
        <span>{money(liveTotal ?? latest.holdingsMarketValue, data.privacy)}</span>
      </div>
      {#if latest.impliedCostBasis != null}
        <div class="kv">
          <span class="k">{t('stocks.overview.totalCost')}</span>
          <span>{money(latest.impliedCostBasis, data.privacy)}</span>
        </div>
      {/if}
      {#if latest.unrealizedGain != null}
        <div class="kv">
          <span class="k">{t('stocks.overview.cumulativePnL')}</span>
          <span class={depositDeltaClass(latest.unrealizedGain)}>
            {signedMoney(latest.unrealizedGain, data.privacy)}
            {#if latest.weightedTotalReturnPct != null}
              <span class="text-secondary inline-meta-tight">
                {latest.weightedTotalReturnPct >= 0 ? '+' : ''}
                {latest.weightedTotalReturnPct.toFixed(2)}%
              </span>
            {/if}
          </span>
        </div>
      {/if}
      {#if latest.todayReturnPctApprox != null}
        <div class="kv">
          <span class="k">{t('stocks.overview.todayPnL')}</span>
          <span class={depositDeltaClass(latest.todayReturnPctApprox)}>
            {#if latest.todayReturnAmountApprox != null}
              {signedMoney(latest.todayReturnAmountApprox, data.privacy)} ·
            {/if}
            {latest.todayReturnPctApprox >= 0 ? '+' : ''}
            {latest.todayReturnPctApprox.toFixed(2)}%
          </span>
        </div>
      {/if}
      <div class="kv">
        <span class="k">{t('stocks.overview.dataAsOf')}</span>
        <span>{snapshotAsOfLabel(latest)}</span>
      </div>
      <div class="kv">
        <span class="k">{t('stocks.overview.quoteStatus')}</span>
        <span class="holdings-overview-live-meta">
          <span
            class="dot {displayStatus === 'live' ? 'ok' : displayStatus === 'error' ? 'critical' : 'warn'}"
          ></span>
          {liveStatusShort(displayStatus)}
          {tabActive ? '' : t('stocks.overview.pausedWhenInactive')}
        </span>
      </div>
      <div class="kv">
        <span class="k">{t('stocks.overview.positionCount')}</span>
        <span>{latest.positionCount}</span>
      </div>
    </div>
    {#if topReturners.length > 0}
      <div class="holdings-overview-movers">
        <span class="label">{t('stocks.overview.topReturners')}</span>
        <ul>
          {#each topReturners as row (row.position.id)}
            <li>
              <span class="holdings-overview-mover-ticker">{row.position.ticker}</span>
              <span class={depositDeltaClass(row.position.totalReturnAmount ?? 0)}>
                {signedMoney(row.position.totalReturnAmount ?? 0, data.privacy)}
              </span>
            </li>
          {/each}
        </ul>
      </div>
    {/if}
  </div>
{/if}
