// apps/finance/src/components/stocks/StocksSummaryKpis.tsx
import { money, signedMoney } from "../../format";
import { useLocale } from "../../i18n/context";

function KpiLabel({ text, tip }: { text: string; tip: string }) {
  const { t } = useLocale();
  return (
    <span className="label">
      {text}
      <span className="help-tip" tabIndex={0} aria-label={t("stocks.kpi.helpTipAria", { label: text })}>
        ?
        <span className="help-tip-pop">{tip}</span>
      </span>
    </span>
  );
}

export function StocksSummaryKpis({
  scope,
  todayReturnAmount,
  todayReturnPct,
  unrealizedGain,
  weightedTotalReturnPct,
  positionCount,
  privacy,
}: {
  scope: {
    totalInvested: number;
    taxableSecurities: number;
    taxableCostBasis?: number;
    retirementBalance: number;
    hsaBalance: number;
    lockedBalance: number;
  };
  todayReturnAmount: number | undefined;
  todayReturnPct: number | undefined;
  unrealizedGain: number | undefined;
  weightedTotalReturnPct: number | undefined;
  positionCount: number;
  privacy: boolean;
}) {
  const { t } = useLocale();
  const { totalInvested, taxableSecurities, taxableCostBasis, lockedBalance, retirementBalance, hsaBalance } =
    scope;
  const hasLocked = lockedBalance > 0;
  const hasTodayAmount = todayReturnAmount != null && Number.isFinite(todayReturnAmount);
  const todayPctLabel =
    todayReturnPct != null && Number.isFinite(todayReturnPct)
      ? `${todayReturnPct >= 0 ? "+" : ""}${todayReturnPct.toFixed(2)}%`
      : "--";
  const todayAmountLabel = hasTodayAmount ? signedMoney(todayReturnAmount as number, privacy) : "--";
  const totalReturnPctLabel =
    weightedTotalReturnPct != null && Number.isFinite(weightedTotalReturnPct)
      ? `${weightedTotalReturnPct >= 0 ? "+" : ""}${weightedTotalReturnPct.toFixed(2)}%`
      : null;
  return (
    <div className="card stocks-kpi-strip">
      <div className="stocks-kpi stocks-kpi-lead">
        <KpiLabel
          text={t("stocks.kpi.investedSnapshot")}
          tip={
            hasLocked
              ? t("stocks.kpi.investedSnapshotTipWithLocked")
              : t("stocks.kpi.investedSnapshotTipTaxableOnly")
          }
        />
        <span className="value">{money(totalInvested, privacy)}</span>
        {hasLocked ? (
          <span className="sub">
            {t("stocks.kpi.taxableSecurities", { amount: money(taxableSecurities, privacy) })}
            {retirementBalance > 0 &&
              t("stocks.kpi.retirement401k", { amount: money(retirementBalance, privacy) })}
            {hsaBalance > 0 && t("stocks.kpi.hsa", { amount: money(hsaBalance, privacy) })}
          </span>
        ) : (
          taxableCostBasis != null &&
          Number.isFinite(taxableCostBasis) && (
            <span className="sub">
              {t("stocks.kpi.totalCostSub", { amount: money(taxableCostBasis, privacy) })}
            </span>
          )
        )}
      </div>
      <div className="stocks-kpi">
        <KpiLabel text={t("stocks.kpi.dailyChange")} tip={t("stocks.kpi.dailyChangeTip")} />
        <span className="value">{todayAmountLabel}</span>
        <span className="sub">{todayPctLabel}</span>
      </div>
      <div className="stocks-kpi">
        <KpiLabel text={t("stocks.kpi.unrealizedGain")} tip={t("stocks.kpi.unrealizedGainTip")} />
        <span className="value">{signedMoney(unrealizedGain ?? 0, privacy)}</span>
        {totalReturnPctLabel && <span className="sub">{totalReturnPctLabel}</span>}
      </div>
      <div className="stocks-kpi">
        <span className="label">{t("stocks.kpi.positionCount")}</span>
        <span className="value">{positionCount}</span>
        <span className="sub">{t("stocks.kpi.positionCountSub")}</span>
      </div>
    </div>
  );
}

// apps/finance/src/lib/components/stocks/StocksSummaryKpis.svelte
<script>
  // Port of StocksSummaryKpis from src/components/stocks/StocksSummaryKpis.tsx.
  import { t } from '$lib/i18n.svelte.js'
  import { money, signedMoney } from '$lib/format.js'

  /** @type {{
   *   scope: {
   *     totalInvested: number,
   *     taxableSecurities: number,
   *     taxableCostBasis?: number,
   *     retirementBalance: number,
   *     hsaBalance: number,
   *     lockedBalance: number,
   *   },
   *   todayReturnAmount?: number,
   *   todayReturnPct?: number,
   *   unrealizedGain?: number,
   *   weightedTotalReturnPct?: number,
   *   positionCount: number,
   *   privacy: boolean,
   * }} */
  let {
    scope,
    todayReturnAmount,
    todayReturnPct,
    unrealizedGain,
    weightedTotalReturnPct,
    positionCount,
    privacy,
  } = $props()

  const hasLocked = $derived(scope.lockedBalance > 0)
  const hasTodayAmount = $derived(
    todayReturnAmount != null && Number.isFinite(todayReturnAmount),
  )
  const todayPctLabel = $derived(
    todayReturnPct != null && Number.isFinite(todayReturnPct)
      ? `${todayReturnPct >= 0 ? '+' : ''}${todayReturnPct.toFixed(2)}%`
      : '--',
  )
  const todayAmountLabel = $derived(
    hasTodayAmount ? signedMoney(/** @type {number} */ (todayReturnAmount), privacy) : '--',
  )
  const totalReturnPctLabel = $derived(
    weightedTotalReturnPct != null && Number.isFinite(weightedTotalReturnPct)
      ? `${weightedTotalReturnPct >= 0 ? '+' : ''}${weightedTotalReturnPct.toFixed(2)}%`
      : null,
  )
</script>

{#snippet kpiLabel(text, tip)}
  <span class="label">
    {text}
    <span class="help-tip" tabindex="0" aria-label={t('stocks.kpi.helpTipAria', { label: text })}>
      ?
      <span class="help-tip-pop">{tip}</span>
    </span>
  </span>
{/snippet}

<div class="card stocks-kpi-strip">
  <div class="stocks-kpi stocks-kpi-lead">
    {@render kpiLabel(
      t('stocks.kpi.investedSnapshot'),
      hasLocked
        ? t('stocks.kpi.investedSnapshotTipWithLocked')
        : t('stocks.kpi.investedSnapshotTipTaxableOnly'),
    )}
    <span class="value">{money(scope.totalInvested, privacy)}</span>
    {#if hasLocked}
      <span class="sub">
        {t('stocks.kpi.taxableSecurities', { amount: money(scope.taxableSecurities, privacy) })}
        {#if scope.retirementBalance > 0}
          {t('stocks.kpi.retirement401k', { amount: money(scope.retirementBalance, privacy) })}
        {/if}
        {#if scope.hsaBalance > 0}
          {t('stocks.kpi.hsa', { amount: money(scope.hsaBalance, privacy) })}
        {/if}
      </span>
    {:else if scope.taxableCostBasis != null && Number.isFinite(scope.taxableCostBasis)}
      <span class="sub">
        {t('stocks.kpi.totalCostSub', { amount: money(scope.taxableCostBasis, privacy) })}
      </span>
    {/if}
  </div>
  <div class="stocks-kpi">
    {@render kpiLabel(t('stocks.kpi.dailyChange'), t('stocks.kpi.dailyChangeTip'))}
    <span class="value">{todayAmountLabel}</span>
    <span class="sub">{todayPctLabel}</span>
  </div>
  <div class="stocks-kpi">
    {@render kpiLabel(t('stocks.kpi.unrealizedGain'), t('stocks.kpi.unrealizedGainTip'))}
    <span class="value">{signedMoney(unrealizedGain ?? 0, privacy)}</span>
    {#if totalReturnPctLabel}<span class="sub">{totalReturnPctLabel}</span>{/if}
  </div>
  <div class="stocks-kpi">
    <span class="label">{t('stocks.kpi.positionCount')}</span>
    <span class="value">{positionCount}</span>
    <span class="sub">{t('stocks.kpi.positionCountSub')}</span>
  </div>
</div>
