// apps/finance/src/components/ForecastView.tsx
import { useState } from "react";
import type { FinanceData, ForecastMetric } from "../types";
import type { Projection } from "../hooks/useProjection";
import type { LiquidCashAnchors } from "../engine/reconciliation";
import { goalReachMonth, metricValue } from "../engine/metrics";
import { ForecastChart } from "./ForecastChart";
import { ForecastSplitChart } from "./ForecastSplitChart";
import { SortBySelect } from "./SortBySelect";
import {
  adjustForDisplay,
  depositDeltaClass,
  money,
  monthOffsetToCalendarLabel,
  pct,
  signedMoney,
} from "../format";
import type { Tab } from "./AppShell";
import {
  accessibleLabel,
  getForecastMetricHints,
  getForecastMetricLabels,
  inTransitCashLabel,
  liquidCashLabel,
  lockedLabel,
} from "../copy/terminology";
import { useLocale } from "../i18n/context";

type ChartMode = "trajectory" | "composition";

/** 与上方时间/视图控件一致：同一套 seg 切换全部口径。 */
const FORECAST_METRICS: ForecastMetric[] = [
  "accessible",
  "liquid",
  "net-worth",
  "invested",
  "locked",
];

export function ForecastView({
  data,
  projection,
  displayLiquidCash,
  cashAnchors,
  onGoTab,
}: {
  data: FinanceData;
  projection: Projection;
  /** 与「今日」页一致：对账锚定后的运营流动现金。 */
  displayLiquidCash?: number;
  cashAnchors?: LiquidCashAnchors;
  onGoTab?: (t: Tab) => void;
}) {
  const { t } = useLocale();
  const maxYears = data.assumptions.horizonYears;
  const horizonOptions = [1, 5, 10, 20, 30].filter((y) => y <= maxYears);
  if (!horizonOptions.includes(maxYears)) horizonOptions.push(maxYears);

  const [years, setYears] = useState<number>(1);
  const [metric, setMetric] = useState<ForecastMetric>("accessible");
  const [chartMode, setChartMode] = useState<ChartMode>("trajectory");
  const [showMetricHint, setShowMetricHint] = useState(false);

  if (data.accounts.length === 0 && data.cashFlows.length === 0) {
    return <div className="empty">{t("forecast.empty")}</div>;
  }

  const read = metricValue(metric);
  const horizonMonths = years * 12;
  const a = data.assumptions;
  const metricLabels = getForecastMetricLabels();
  const metricHints = getForecastMetricHints();
  const accessible = accessibleLabel();
  const locked = lockedLabel();
  const liquidCash = liquidCashLabel();
  const inTransitCash = inTransitCashLabel();
  const privacy = data.privacy;
  const endIdx = Math.min(horizonMonths, projection.baseline.length - 1);
  const endSnap = projection.baseline[endIdx];
  const nowSnap = projection.baseline[0];

  const adj = (v: number, m: number) => adjustForDisplay(v, m, a.displayMode, a.inflation);

  const todayVal = adj(read(nowSnap), 0);
  const endVal = adj(read(endSnap), endIdx);
  const delta = endVal - todayVal;

  const liquidToday = displayLiquidCash ?? nowSnap.liquidCash;
  const capGainsRate = Math.min(1, Math.max(0, a.capitalGainsTaxRate ?? 0.15));
  const brokerageTax = {
    market: nowSnap.investedTaxable,
    basis: nowSnap.investedTaxableBasis,
    gain: nowSnap.unrealizedGainEstimate,
    tax: nowSnap.capitalGainsTaxEstimate,
    afterTax: nowSnap.investedTaxableAfterTax,
    basisKnown: nowSnap.taxBasisKnown,
  };

  const lowVal = adj(
    read(projection.conservative[endIdx]),
    endIdx
  );
  const highVal = adj(
    read(projection.aggressive[endIdx]),
    endIdx
  );

  const accessibleEnd = adj(endSnap.accessible, endIdx);
  const lockedEnd = adj(endSnap.locked, endIdx);
  const totalSplit = accessibleEnd + lockedEnd;
  const accessiblePct = totalSplit > 0 ? accessibleEnd / totalSplit : 0;

  const reaching = data.goals
    .filter((g) => g.metric === metric)
    .map((g) => ({ goal: g, month: goalReachMonth(projection.baseline, g) }))
    .filter((x) => x.month != null && (x.month as number) <= horizonMonths)
    .sort((a, b) => (a.month as number) - (b.month as number))
    .slice(0, 3);

  const displayModeNote =
    a.displayMode === "today" ? t("forecast.displayToday") : t("forecast.displayFuture");

  return (
    <div className="grid gap-4">
      <div className="card forecast-card">
        {onGoTab && (
          <div className="forecast-card-head">
            <button type="button" className="btn outline compact" onClick={() => onGoTab("settings")}>
              {t("forecast.editAssumptions")}
            </button>
          </div>
        )}

        <div className="forecast-controls-mobile chart-controls">
          <SortBySelect
            label={t("forecast.horizonLabel")}
            compact
            value={String(years)}
            onChange={(v) => setYears(Number(v))}
            options={horizonOptions.map((y) => ({ id: String(y), label: t("forecast.yearsShort", { y: String(y) }) }))}
          />
          <SortBySelect
            label={t("forecast.metricLabel")}
            compact
            value={metric}
            onChange={(v) => setMetric(v as ForecastMetric)}
            options={FORECAST_METRICS.map((m) => ({ id: m, label: metricLabels[m] }))}
          />
          <span className="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge forecast-chart-mode-seg">
            <button
              type="button"
              className={chartMode === "trajectory" ? "active" : ""}
              onClick={() => setChartMode("trajectory")}
            >
              {t("forecast.chartTrajectory")}
            </button>
            <button
              type="button"
              className={chartMode === "composition" ? "active" : ""}
              onClick={() => setChartMode("composition")}
            >
              {accessible} / {locked}
            </button>
          </span>
          <button
            type="button"
            className="icon-btn forecast-hint-btn"
            aria-expanded={showMetricHint}
            aria-label={t("forecast.metricHintAria", { metric: metricLabels[metric] })}
            title={t("forecast.metricHintTitle")}
            onClick={() => setShowMetricHint((v) => !v)}
          >
            ⓘ
          </button>
        </div>

        <div className="forecast-controls-desktop">
          <div className="chart-controls forecast-controls">
            <span className="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge">
              {horizonOptions.map((y) => (
                <button
                  key={y}
                  type="button"
                  className={years === y ? "active" : ""}
                  onClick={() => setYears(y)}
                >
                  {t("forecast.yearsShort", { y: String(y) })}
                </button>
              ))}
            </span>
            <span className="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge">
              <button
                type="button"
                className={chartMode === "trajectory" ? "active" : ""}
                onClick={() => setChartMode("trajectory")}
              >
                {t("forecast.chartTrajectory")}
              </button>
              <button
                type="button"
                className={chartMode === "composition" ? "active" : ""}
                onClick={() => setChartMode("composition")}
              >
                {accessible} / {locked}
              </button>
            </span>
          </div>

          <div className="chart-controls forecast-controls forecast-controls-metrics mt-2">
            <div className="forecast-controls-cluster">
              <span className="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge forecast-metric-seg" role="group" aria-label={t("forecast.metricLabel")}>
                {FORECAST_METRICS.map((m) => (
                  <button
                    key={m}
                    type="button"
                    className={metric === m ? "active" : ""}
                    onClick={() => setMetric(m)}
                  >
                    {metricLabels[m]}
                  </button>
                ))}
              </span>
              <button
                type="button"
                className="icon-btn forecast-hint-btn"
                aria-expanded={showMetricHint}
                aria-label={t("forecast.metricHintAria", { metric: metricLabels[metric] })}
                title={t("forecast.metricHintTitle")}
                onClick={() => setShowMetricHint((v) => !v)}
              >
                ⓘ
              </button>
            </div>
            <div className="forecast-controls-cluster forecast-controls-cluster-end">
              <span className="text-muted forecast-display-mode">{displayModeNote}</span>
            </div>
          </div>
        </div>

        {showMetricHint && (
          <p className="muted-note forecast-metric-hint">
            {metricHints[metric]}
            <span className="text-muted"> · {displayModeNote}</span>
          </p>
        )}

        <div className="forecast-hero">
          <div className="forecast-hero-main">
            <span className="text-secondary">
              {t("forecast.metricRange", { metric: metricLabels[metric], years: String(years) })}
            </span>
            <div className="forecast-hero-values">
              <span className="forecast-hero-today">{money(todayVal, privacy)}</span>
              <span className="forecast-hero-arrow text-muted">→</span>
              <span className="pr-value">{money(endVal, privacy)}</span>
              <span className={`forecast-hero-delta ${depositDeltaClass(delta)}`}>
                {signedMoney(delta, privacy)}
              </span>
            </div>
            {metric === "accessible" && (
              <p className="forecast-hero-breakdown text-muted">
                {t("forecast.todayBreakdown")}
                {cashAnchors?.hasAnchoredAccounts ? inTransitCash : liquidCash}{" "}
                {money(liquidToday, privacy)}
                {nowSnap.reserve > 0 && (
                  <> {t("forecast.reservePart", { amount: money(nowSnap.reserve, privacy) })}</>
                )}
                {brokerageTax.market > 0 && (
                  <>
                    {" "}
                    {brokerageTax.basisKnown ? (
                      t("forecast.brokerageTaxFull", {
                        market: money(brokerageTax.market, privacy),
                        basis: money(brokerageTax.basis, privacy),
                        gain: money(brokerageTax.gain, privacy),
                        tax: money(brokerageTax.tax, privacy),
                        rate: pct(capGainsRate),
                        afterTax: money(brokerageTax.afterTax, privacy),
                      })
                    ) : (
                      t("forecast.brokerageNoBasis", {
                        market: money(brokerageTax.market, privacy),
                      })
                    )}
                  </>
                )}
                {nowSnap.property > 0 && (
                  <> {t("forecast.propertyPart", { amount: money(nowSnap.property, privacy) })}</>
                )}
                {nowSnap.liabilities > 0 && (
                  <> {t("forecast.liabilitiesPart", { amount: money(nowSnap.liabilities, privacy) })}</>
                )}
              </p>
            )}
            {metric === "liquid" && cashAnchors?.hasAnchoredAccounts && (
              <p className="forecast-hero-breakdown text-muted">
                {t("forecast.inTransitNote", { amount: money(cashAnchors.cacheLiquid, privacy) })}
              </p>
            )}
          </div>
          {chartMode === "trajectory" && (
            <p className="forecast-hero-range text-secondary">
              {t("forecast.rangeNote", {
                years: String(years),
                conservative: pct(a.conservativeReturn),
                baseline: pct(a.baselineReturn),
                aggressive: pct(a.aggressiveReturn),
                low: money(lowVal, privacy),
                high: money(highVal, privacy),
              })}
            </p>
          )}
          {chartMode === "composition" && (
            <p className="forecast-hero-range text-secondary">
              {t("forecast.endSplit", {
                years: String(years),
                accessible,
                locked,
                amount: money(accessibleEnd, privacy),
                pct: pct(accessiblePct),
                lockedAmount: money(lockedEnd, privacy),
              })}
            </p>
          )}
        </div>

        {chartMode === "trajectory" ? (
          <ForecastChart
            baseline={projection.baseline}
            low={projection.conservative}
            high={projection.aggressive}
            read={read}
            displayMode={a.displayMode}
            inflation={a.inflation}
            horizonMonths={horizonMonths}
            privacy={privacy}
          />
        ) : (
          <ForecastSplitChart
            baseline={projection.baseline}
            displayMode={a.displayMode}
            inflation={a.inflation}
            horizonMonths={horizonMonths}
            privacy={privacy}
          />
        )}

        {chartMode === "trajectory" && metric !== "locked" && (
          <p className="forecast-composition-strip text-secondary">
            {t("forecast.endComposition", {
              years: String(years),
              accessible,
              locked,
              amount: money(accessibleEnd, privacy),
              pct: pct(accessiblePct),
              lockedAmount: money(lockedEnd, privacy),
            })}
          </p>
        )}

        {reaching.length > 0 && (
          <div className="forecast-milestones">
            <span className="text-secondary">
              {t("forecast.goalsInWindow", { metric: metricLabels[metric] })}
            </span>
            <ul className="forecast-milestone-list">
              {reaching.map((r) => (
                <li key={r.goal.id}>
                  <div className="forecast-milestone-main">
                    <span className="forecast-milestone-name">{r.goal.name}</span>
                    <span className="forecast-milestone-meta">
                      {t("forecast.goalTarget", { amount: money(r.goal.target, privacy) })}
                    </span>
                  </div>
                  <span className="forecast-milestone-when text-muted">
                    {t("forecast.goalEta", { when: monthOffsetToCalendarLabel(r.month as number) })}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {reaching.length === 0 && data.goals.some((g) => g.metric !== metric) && (
          <p className="muted-note">
            {t("forecast.noGoalsInWindow", { years: String(years) })}
            {onGoTab && (
              <>
                {" "}
                <button type="button" className="text-btn" onClick={() => onGoTab("overview")}>
                  {t("forecast.viewAllGoals")}
                </button>
              </>
            )}
          </p>
        )}

        <p className="muted-note forecast-disclaimer">
          {t("forecast.disclaimer")}
        </p>
      </div>
    </div>
  );
}

// apps/finance/src/lib/components/ForecastView.svelte
<script>
  // Port of src/components/ForecastView.tsx.
  import { t } from '$lib/i18n.svelte.js'
  import {
    adjustForDisplay,
    depositDeltaClass,
    money,
    monthOffsetToCalendarLabel,
    pct,
    signedMoney,
  } from '$lib/format.js'
  import {
    accessibleLabel,
    getForecastMetricHints,
    getForecastMetricLabels,
    inTransitCashLabel,
    liquidCashLabel,
    lockedLabel,
  } from '../../copy/terminology.js'
  import { goalReachMonth, metricValue } from '../../engine/metrics.js'
  import ForecastChart from './ForecastChart.svelte'
  import ForecastSplitChart from './ForecastSplitChart.svelte'
  import SortBySelect from './SortBySelect.svelte'

  /** @typedef {import('../../types.js').FinanceData} FinanceData */
  /** @typedef {import('../../types.js').ForecastMetric} ForecastMetric */
  /** @typedef {import('$lib/projection.js').computeProjection} _cp */

  /** @type {{
   *   data: FinanceData,
   *   projection: ReturnType<typeof import('$lib/projection.js').computeProjection>,
   *   displayLiquidCash?: number,
   *   cashAnchors?: import('../../engine/reconciliation.js').LiquidCashAnchors,
   *   onGoTab?: (tab: string, section?: string) => void,
   * }} */
  let { data, projection, displayLiquidCash, cashAnchors, onGoTab } = $props()

  const FORECAST_METRICS = /** @type {ForecastMetric[]} */ ([
    'accessible',
    'liquid',
    'net-worth',
    'invested',
    'locked',
  ])

  const maxYears = $derived(data.assumptions.horizonYears)
  const horizonOptions = $derived.by(() => {
    const opts = [1, 5, 10, 20, 30].filter((y) => y <= maxYears)
    if (!opts.includes(maxYears)) opts.push(maxYears)
    return opts
  })

  let years = $state(1)
  let metric = $state(/** @type {ForecastMetric} */ ('accessible'))
  let chartMode = $state(/** @type {'trajectory' | 'composition'} */ ('trajectory'))
  let showMetricHint = $state(false)

  const read = $derived(metricValue(metric))
  const horizonMonths = $derived(years * 12)
  const a = $derived(data.assumptions)
  const metricLabels = $derived(getForecastMetricLabels())
  const metricHints = $derived(getForecastMetricHints())
  const accessible = $derived(accessibleLabel())
  const locked = $derived(lockedLabel())
  const liquidCash = $derived(liquidCashLabel())
  const inTransitCash = $derived(inTransitCashLabel())
  const privacy = $derived(data.privacy)
  const endIdx = $derived(Math.min(horizonMonths, projection.baseline.length - 1))
  const endSnap = $derived(projection.baseline[endIdx])
  const nowSnap = $derived(projection.baseline[0])

  /** @param {number} v @param {number} m */
  function adj(v, m) {
    return adjustForDisplay(v, m, a.displayMode, a.inflation)
  }

  const todayVal = $derived(adj(read(nowSnap), 0))
  const endVal = $derived(adj(read(endSnap), endIdx))
  const delta = $derived(endVal - todayVal)
  const liquidToday = $derived(displayLiquidCash ?? nowSnap.liquidCash)
  const capGainsRate = $derived(Math.min(1, Math.max(0, a.capitalGainsTaxRate ?? 0.15)))
  const brokerageTax = $derived({
    market: nowSnap.investedTaxable,
    basis: nowSnap.investedTaxableBasis,
    gain: nowSnap.unrealizedGainEstimate,
    tax: nowSnap.capitalGainsTaxEstimate,
    afterTax: nowSnap.investedTaxableAfterTax,
    basisKnown: nowSnap.taxBasisKnown,
  })
  const lowVal = $derived(adj(read(projection.conservative[endIdx]), endIdx))
  const highVal = $derived(adj(read(projection.aggressive[endIdx]), endIdx))
  const accessibleEnd = $derived(adj(endSnap.accessible, endIdx))
  const lockedEnd = $derived(adj(endSnap.locked, endIdx))
  const totalSplit = $derived(accessibleEnd + lockedEnd)
  const accessiblePct = $derived(totalSplit > 0 ? accessibleEnd / totalSplit : 0)
  const reaching = $derived(
    data.goals
      .filter((g) => g.metric === metric)
      .map((g) => ({ goal: g, month: goalReachMonth(projection.baseline, g) }))
      .filter((x) => x.month != null && /** @type {number} */ (x.month) <= horizonMonths)
      .sort((a, b) => /** @type {number} */ (a.month) - /** @type {number} */ (b.month))
      .slice(0, 3),
  )
  const displayModeNote = $derived(
    a.displayMode === 'today' ? t('forecast.displayToday') : t('forecast.displayFuture'),
  )
</script>

{#if data.accounts.length === 0 && data.cashFlows.length === 0}
  <div class="empty">{t('forecast.empty')}</div>
{:else}
  <div class="grid gap-4">
    <div class="card forecast-card">
      {#if onGoTab}
        <div class="forecast-card-head">
          <button
            type="button"
            class="btn outline compact"
            onclick={() => onGoTab('settings', 'assumptions')}
          >
            {t('forecast.editAssumptions')}
          </button>
        </div>
      {/if}

      <div class="forecast-controls-mobile chart-controls">
        <SortBySelect
          label={t('forecast.horizonLabel')}
          compact
          value={String(years)}
          onChange={(v) => (years = Number(v))}
          options={horizonOptions.map((y) => ({
            id: String(y),
            label: t('forecast.yearsShort', { y: String(y) }),
          }))}
        />
        <SortBySelect
          label={t('forecast.metricLabel')}
          compact
          value={metric}
          onChange={(v) => (metric = /** @type {ForecastMetric} */ (v))}
          options={FORECAST_METRICS.map((m) => ({ id: m, label: metricLabels[m] }))}
        />
        <span class="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge forecast-chart-mode-seg">
          <button
            type="button"
            class={chartMode === 'trajectory' ? 'active' : ''}
            onclick={() => (chartMode = 'trajectory')}
          >
            {t('forecast.chartTrajectory')}
          </button>
          <button
            type="button"
            class={chartMode === 'composition' ? 'active' : ''}
            onclick={() => (chartMode = 'composition')}
          >
            {accessible} / {locked}
          </button>
        </span>
        <button
          type="button"
          class="icon-btn forecast-hint-btn"
          aria-expanded={showMetricHint}
          aria-label={t('forecast.metricHintAria', { metric: metricLabels[metric] })}
          title={t('forecast.metricHintTitle')}
          onclick={() => (showMetricHint = !showMetricHint)}
        >
          ⓘ
        </button>
      </div>

      <div class="forecast-controls-desktop">
        <div class="chart-controls forecast-controls">
          <span class="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge">
            {#each horizonOptions as y (y)}
              <button
                type="button"
                class={years === y ? 'active' : ''}
                onclick={() => (years = y)}
              >
                {t('forecast.yearsShort', { y: String(y) })}
              </button>
            {/each}
          </span>
          <span class="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge">
            <button
              type="button"
              class={chartMode === 'trajectory' ? 'active' : ''}
              onclick={() => (chartMode = 'trajectory')}
            >
              {t('forecast.chartTrajectory')}
            </button>
            <button
              type="button"
              class={chartMode === 'composition' ? 'active' : ''}
              onclick={() => (chartMode = 'composition')}
            >
              {accessible} / {locked}
            </button>
          </span>
        </div>
        <div class="chart-controls forecast-controls forecast-controls-metrics mt-2">
          <div class="forecast-controls-cluster">
            <span
              class="seg seg-scroll life-os-scroll-x life-os-scroll-x--snap life-os-scroll-x--fade-edge forecast-metric-seg"
              role="group"
              aria-label={t('forecast.metricLabel')}
            >
              {#each FORECAST_METRICS as m (m)}
                <button
                  type="button"
                  class={metric === m ? 'active' : ''}
                  onclick={() => (metric = m)}
                >
                  {metricLabels[m]}
                </button>
              {/each}
            </span>
            <button
              type="button"
              class="icon-btn forecast-hint-btn"
              aria-expanded={showMetricHint}
              aria-label={t('forecast.metricHintAria', { metric: metricLabels[metric] })}
              title={t('forecast.metricHintTitle')}
              onclick={() => (showMetricHint = !showMetricHint)}
            >
              ⓘ
            </button>
          </div>
          <div class="forecast-controls-cluster forecast-controls-cluster-end">
            <span class="text-muted forecast-display-mode">{displayModeNote}</span>
          </div>
        </div>
      </div>

      {#if showMetricHint}
        <p class="muted-note forecast-metric-hint">
          {metricHints[metric]}
          <span class="text-muted"> · {displayModeNote}</span>
        </p>
      {/if}

      <div class="forecast-hero">
        <div class="forecast-hero-main">
          <span class="text-secondary">
            {t('forecast.metricRange', { metric: metricLabels[metric], years: String(years) })}
          </span>
          <div class="forecast-hero-values">
            <span class="forecast-hero-today">{money(todayVal, privacy)}</span>
            <span class="forecast-hero-arrow text-muted">→</span>
            <span class="pr-value">{money(endVal, privacy)}</span>
            <span class="forecast-hero-delta {depositDeltaClass(delta)}">
              {signedMoney(delta, privacy)}
            </span>
          </div>
          {#if metric === 'accessible'}
            <p class="forecast-hero-breakdown text-muted">
              {t('forecast.todayBreakdown')}
              {cashAnchors?.hasAnchoredAccounts ? inTransitCash : liquidCash}
              {money(liquidToday, privacy)}
              {#if nowSnap.reserve > 0}
                {t('forecast.reservePart', { amount: money(nowSnap.reserve, privacy) })}
              {/if}
              {#if brokerageTax.market > 0}
                {#if brokerageTax.basisKnown}
                  {t('forecast.brokerageTaxFull', {
                    market: money(brokerageTax.market, privacy),
                    basis: money(brokerageTax.basis, privacy),
                    gain: money(brokerageTax.gain, privacy),
                    tax: money(brokerageTax.tax, privacy),
                    rate: pct(capGainsRate),
                    afterTax: money(brokerageTax.afterTax, privacy),
                  })}
                {:else}
                  {t('forecast.brokerageNoBasis', { market: money(brokerageTax.market, privacy) })}
                {/if}
              {/if}
              {#if nowSnap.property > 0}
                {t('forecast.propertyPart', { amount: money(nowSnap.property, privacy) })}
              {/if}
              {#if nowSnap.liabilities > 0}
                {t('forecast.liabilitiesPart', { amount: money(nowSnap.liabilities, privacy) })}
              {/if}
            </p>
          {/if}
          {#if metric === 'liquid' && cashAnchors?.hasAnchoredAccounts}
            <p class="forecast-hero-breakdown text-muted">
              {t('forecast.inTransitNote', { amount: money(cashAnchors.cacheLiquid, privacy) })}
            </p>
          {/if}
        </div>
        {#if chartMode === 'trajectory'}
          <p class="forecast-hero-range text-secondary">
            {t('forecast.rangeNote', {
              years: String(years),
              conservative: pct(a.conservativeReturn),
              baseline: pct(a.baselineReturn),
              aggressive: pct(a.aggressiveReturn),
              low: money(lowVal, privacy),
              high: money(highVal, privacy),
            })}
          </p>
        {:else}
          <p class="forecast-hero-range text-secondary">
            {t('forecast.endSplit', {
              years: String(years),
              accessible,
              locked,
              amount: money(accessibleEnd, privacy),
              pct: pct(accessiblePct),
              lockedAmount: money(lockedEnd, privacy),
            })}
          </p>
        {/if}
      </div>

      {#if chartMode === 'trajectory'}
        <ForecastChart
          baseline={projection.baseline}
          low={projection.conservative}
          high={projection.aggressive}
          read={read}
          displayMode={a.displayMode}
          inflation={a.inflation}
          horizonMonths={horizonMonths}
          {privacy}
        />
      {:else}
        <ForecastSplitChart
          baseline={projection.baseline}
          displayMode={a.displayMode}
          inflation={a.inflation}
          horizonMonths={horizonMonths}
          {privacy}
        />
      {/if}

      {#if chartMode === 'trajectory' && metric !== 'locked'}
        <p class="forecast-composition-strip text-secondary">
          {t('forecast.endComposition', {
            years: String(years),
            accessible,
            locked,
            amount: money(accessibleEnd, privacy),
            pct: pct(accessiblePct),
            lockedAmount: money(lockedEnd, privacy),
          })}
        </p>
      {/if}

      {#if reaching.length > 0}
        <div class="forecast-milestones">
          <span class="text-secondary">
            {t('forecast.goalsInWindow', { metric: metricLabels[metric] })}
          </span>
          <ul class="forecast-milestone-list">
            {#each reaching as r (r.goal.id)}
              <li>
                <div class="forecast-milestone-main">
                  <span class="forecast-milestone-name">{r.goal.name}</span>
                  <span class="forecast-milestone-meta">
                    {t('forecast.goalTarget', { amount: money(r.goal.target, privacy) })}
                  </span>
                </div>
                <span class="forecast-milestone-when text-muted">
                  {t('forecast.goalEta', {
                    when: monthOffsetToCalendarLabel(/** @type {number} */ (r.month)),
                  })}
                </span>
              </li>
            {/each}
          </ul>
        </div>
      {:else if data.goals.some((g) => g.metric !== metric)}
        <p class="muted-note">
          {t('forecast.noGoalsInWindow', { years: String(years) })}
          {#if onGoTab}
            <button type="button" class="text-btn" onclick={() => onGoTab('home', 'overview')}>
              {t('forecast.viewAllGoals')}
            </button>
          {/if}
        </p>
      {/if}

      <p class="muted-note forecast-disclaimer">{t('forecast.disclaimer')}</p>
    </div>
  </div>
{/if}
