// apps/finance/src/components/SortBySelect.tsx
type SortOption<T extends string> = {
  id: T;
  label: string;
};

export function SortBySelect<T extends string>({
  label = "排序",
  value,
  onChange,
  options,
  className,
  compact = false,
}: {
  label?: string;
  value: T;
  onChange: (next: T) => void;
  options: SortOption<T>[];
  className?: string;
  compact?: boolean;
}) {
  return (
    <div className={["field", "sort-select", compact ? "compact" : "", className].filter(Boolean).join(" ")}>
      {!compact && <label>{label}</label>}
      <select
        className="input"
        value={value}
        aria-label={label}
        onChange={(e) => onChange(e.target.value as T)}
      >
        {options.map((option) => (
          <option key={option.id} value={option.id}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
}

// apps/finance/src/lib/components/SortBySelect.svelte
<script>
  // 端口自 src/components/SortBySelect.tsx。
  let { label = '排序', value, onChange, options, className, compact = false } = $props()

  const classes = $derived(
    ['field', 'sort-select', compact ? 'compact' : '', className].filter(Boolean).join(' '),
  )
</script>

<div class={classes}>
  {#if !compact}<label>{label}</label>{/if}
  <select class="input" {value} aria-label={label} onchange={(e) => onChange(e.currentTarget.value)}>
    {#each options as option (option.id)}
      <option value={option.id}>{option.label}</option>
    {/each}
  </select>
</div>
