// apps/finance/src/components/SpendingTrendChart.tsx
import {
  Bar,
  CartesianGrid,
  ComposedChart,
  Line,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import type { MonthPoint } from "../engine/transactions";
import { money, moneyCompact } from "../format";

/** 月度花销(柱) + 收入(线) 趋势图。 */
export function SpendingTrendChart({
  series,
  privacy,
}: {
  series: MonthPoint[];
  privacy: boolean;
}) {
  const data = series.map((p) => ({
    month: p.month,
    spending: Math.round(p.spending),
    income: Math.round(p.income),
  }));

  return (
    <div className="spending-chart-wrap">
      <ResponsiveContainer>
        <ComposedChart data={data} margin={{ top: 8, right: 12, bottom: 0, left: 4 }}>
          <CartesianGrid stroke="var(--border)" vertical={false} />
          <XAxis
            dataKey="month"
            tickFormatter={(m: string) => m.slice(2)}
            interval="preserveStartEnd"
            minTickGap={28}
            stroke="var(--border-strong)"
          />
          <YAxis
            width={56}
            tickFormatter={(v: number) => (privacy ? "•" : moneyCompact(v))}
            stroke="var(--border-strong)"
          />
          <Tooltip
            contentStyle={{
              background: "var(--bg-elevated)",
              border: "1px solid var(--border-strong)",
              borderRadius: 8,
              color: "var(--text)",
            }}
            labelFormatter={(m) => `${m}`}
            formatter={(value, name) => {
              const label = name === "spending" ? "花销" : "收入";
              return [money(Number(value), privacy), label];
            }}
          />
          <Bar
            dataKey="spending"
            fill="var(--accent-dim)"
            radius={[3, 3, 0, 0]}
            maxBarSize={48}
            isAnimationActive={false}
          />
          <Line
            dataKey="income"
            stroke="var(--positive)"
            strokeWidth={2}
            dot={false}
            isAnimationActive={false}
          />
        </ComposedChart>
      </ResponsiveContainer>
    </div>
  );
}

// apps/finance/src/lib/components/SpendingTrendChart.svelte
<script>
  // Port of src/components/SpendingTrendChart.tsx (SVG chart; avoids React-only recharts).
  import { money, moneyCompact } from '$lib/format.js'

  /** @type {{ series: import('../../engine/transactions.js').MonthPoint[], privacy: boolean }} */
  let { series, privacy } = $props()

  const data = $derived(
    series.map((p) => ({
      month: p.month,
      spending: Math.round(p.spending),
      income: Math.round(p.income),
    })),
  )

  const maxY = $derived(Math.max(1, ...data.map((d) => Math.max(d.spending, d.income))))
  const chartW = 640
  const chartH = 200
  const padL = 56
  const padR = 12
  const padT = 8
  const padB = 24
  const innerW = chartW - padL - padR
  const innerH = chartH - padT - padB
  const barW = $derived(data.length > 0 ? Math.min(48, innerW / data.length - 4) : 24)

  /** @param {number} v */
  function yScale(v) {
    return padT + innerH - (v / maxY) * innerH
  }

  /** @param {number} i */
  function xCenter(i) {
    const step = data.length > 1 ? innerW / (data.length - 1) : innerW / 2
    return padL + (data.length > 1 ? i * step : innerW / 2)
  }

  const linePoints = $derived(
    data.map((d, i) => `${xCenter(i)},${yScale(d.income)}`).join(' '),
  )
</script>

<div class="spending-chart-wrap">
  <svg viewBox="0 0 {chartW} {chartH}" width="100%" height={chartH} role="img" aria-hidden="true">
    {#each [0, 0.25, 0.5, 0.75, 1] as tick (tick)}
      {@const y = padT + innerH * (1 - tick)}
      <line x1={padL} y1={y} x2={chartW - padR} y2={y} stroke="var(--border)" />
      <text
        x={padL - 6}
        y={y + 4}
        text-anchor="end"
        fill="var(--border-strong)"
        font-size="10"
      >
        {privacy ? '•' : moneyCompact(maxY * tick)}
      </text>
    {/each}

    {#each data as d, i (d.month)}
      {@const cx = xCenter(i)}
      {@const barH = Math.max(0, innerH - (yScale(d.spending) - padT))}
      <rect
        x={cx - barW / 2}
        y={yScale(d.spending)}
        width={barW}
        height={barH}
        rx="3"
        fill="var(--accent-dim)"
      />
      <text x={cx} y={chartH - 6} text-anchor="middle" fill="var(--border-strong)" font-size="10">
        {d.month.slice(2)}
      </text>
    {/each}

    {#if data.length > 1}
      <polyline
        points={linePoints}
        fill="none"
        stroke="var(--positive)"
        stroke-width="2"
      />
    {:else if data.length === 1}
      <circle cx={xCenter(0)} cy={yScale(data[0].income)} r="3" fill="var(--positive)" />
    {/if}
  </svg>
</div>
