// apps/finance/src/components/SyncErrorBanner.tsx
import { useEffect, useState } from "react";
import { subscribeSyncError } from "../lib/syncNotify";
import { useLocale } from "../i18n/context";

export function SyncErrorBanner() {
  const { t } = useLocale();
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    return subscribeSyncError((msg) => setMessage(msg));
  }, []);

  if (!message) return null;

  return (
    <div className="banner critical banner--row" role="alert">
      <span>
        {t("sync.bannerPrefix")}
        {message}
        {t("sync.bannerSuffix")}
      </span>
      <button
        type="button"
        className="btn ghost compact"
        onClick={() => setMessage(null)}
      >
        {t("common.close")}
      </button>
    </div>
  );
}

// apps/planner/src/lib/components/SyncErrorBanner.svelte
<script>
  import { onMount } from 'svelte';
  import { subscribeSyncError } from '$lib/syncNotify.js';
  import { t } from '$lib/i18n/index.js';

  let message = $state(null);

  onMount(() => subscribeSyncError((msg) => {
    message = msg;
  }));

  function dismiss() {
    message = null;
  }
</script>

{#if message}
  <div class="banner critical banner--row banner--fixed" role="alert" aria-live="assertive">
    <span class="banner__text">{t('sync.bannerPrefix')}{message}{t('sync.bannerSuffix')}</span>
    <button type="button" class="btn-ghost banner-close" onclick={dismiss}>{t('common.close')}</button>
  </div>
{/if}
