// apps/finance/src/lib/components/CashflowQuickAddDrawer.svelte
<script>
  // Port of src/components/CashflowQuickAddDrawer.tsx.
  import { getFinanceStore, uid } from '$lib/finance.svelte.js'
  import { signedMonthOffset } from '../../engine/calendar.js'
  import DateField from './fields/DateField.svelte'
  import NumberField from './fields/NumberField.svelte'
  import TextField from './fields/TextField.svelte'

  /** @type {{ onClose: () => void }} */
  let { onClose } = $props()

  const store = getFinanceStore()

  /** @typedef {'income' | 'expense'} Kind */

  /** @type {Kind} */
  let kind = $state('expense')
  let amount = $state(0)
  let name = $state('')

  function todayISO() {
    const d = new Date()
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
  }

  let date = $state(todayISO())

  /** @param {Kind} k @param {string} d @param {number} amt @param {string} n */
  function makeEvent(k, d, amt, n) {
    const now = new Date()
    return {
      id: uid('evt'),
      name: n.trim() || (k === 'income' ? '一次性收入' : '一次性支出'),
      eventType: k === 'income' ? 'windfall' : 'one-time-purchase',
      enabled: true,
      amount: amt,
      date: d,
      monthOffset: signedMonthOffset(now, d),
      fundingSource: k === 'expense' ? 'checking' : undefined,
    }
  }

  /** @param {SubmitEvent} e */
  function add(e) {
    e.preventDefault()
    if (amount <= 0) return
    store.upsertEvent(makeEvent(kind, date, amount, name))
    onClose()
  }
</script>

<div class="drawer-backdrop" onclick={onClose} role="presentation"></div>
<aside class="drawer">
  <div class="drawer-head">
    <h2>添加一次性收支</h2>
    <button type="button" class="icon-btn" onclick={onClose}>关闭</button>
  </div>

  <form onsubmit={add}>
    <div class="seg mb-3">
      <button type="button" class={kind === 'expense' ? 'active' : ''} onclick={() => (kind = 'expense')}>
        支出
      </button>
      <button type="button" class={kind === 'income' ? 'active' : ''} onclick={() => (kind = 'income')}>
        收入
      </button>
    </div>

    <NumberField label="金额" value={amount} onChange={(v) => (amount = v)} step={50} min={0} />
    <TextField
      label="名称"
      value={name}
      onChange={(v) => (name = v)}
      placeholder={kind === 'income' ? '如：报税退款 / 奖金' : '如：旅行 / 买设备 / 看病'}
    />
    <DateField label="日期" value={date} onChange={(v) => (date = v || todayISO())} />

    <p class="meta mt-3 mb-0">过去的日期会记为「已发生」，不计入未来预测，只用于记录与对账。</p>

    <button class="btn mt-4 w-full" type="submit" disabled={amount <= 0}>添加</button>
  </form>
</aside>

// apps/finance/src/components/CashflowQuickAddDrawer.tsx
import { useState } from "react";
import { useFinance, uid } from "../store/store";
import type { ScenarioEvent } from "../types";
import { signedMonthOffset } from "../engine/calendar";
import { DateField, NumberField, TextField } from "./fields";

type Kind = "income" | "expense";

function todayISO(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
    d.getDate()
  ).padStart(2, "0")}`;
}

function makeEvent(kind: Kind, date: string, amount: number, name: string): ScenarioEvent {
  const now = new Date();
  return {
    id: uid("evt"),
    name: name.trim() || (kind === "income" ? "一次性收入" : "一次性支出"),
    eventType: kind === "income" ? "windfall" : "one-time-purchase",
    enabled: true,
    amount,
    date,
    monthOffset: signedMonthOffset(now, date),
    fundingSource: kind === "expense" ? "checking" : undefined,
  };
}

export function CashflowQuickAddDrawer({ onClose }: { onClose: () => void }) {
  const store = useFinance();
  const [kind, setKind] = useState<Kind>("expense");
  const [amount, setAmount] = useState(0);
  const [name, setName] = useState("");
  const [date, setDate] = useState(todayISO());

  const add = (e: React.FormEvent) => {
    e.preventDefault();
    if (amount <= 0) return;
    store.upsertEvent(makeEvent(kind, date, amount, name));
    onClose();
  };

  return (
    <>
      <div className="drawer-backdrop" onClick={onClose} />
      <aside className="drawer">
        <div className="drawer-head">
          <h2>添加一次性收支</h2>
          <button type="button" className="icon-btn" onClick={onClose}>
            关闭
          </button>
        </div>

        <form onSubmit={add}>
          <div className="seg mb-3">
            <button
              type="button"
              className={kind === "expense" ? "active" : ""}
              onClick={() => setKind("expense")}
            >
              支出
            </button>
            <button
              type="button"
              className={kind === "income" ? "active" : ""}
              onClick={() => setKind("income")}
            >
              收入
            </button>
          </div>

          <NumberField label="金额" value={amount} onChange={setAmount} step={50} min={0} />
          <TextField
            label="名称"
            value={name}
            onChange={setName}
            placeholder={
              kind === "income" ? "如：报税退款 / 奖金" : "如：旅行 / 买设备 / 看病"
            }
          />
          <DateField label="日期" value={date} onChange={(v) => setDate(v || todayISO())} />

          <p className="meta mt-3 mb-0">
            过去的日期会记为「已发生」，不计入未来预测，只用于记录与对账。
          </p>

          <button
            className="btn mt-4 w-full"
            type="submit"
            disabled={amount <= 0}
          >
            添加
          </button>
        </form>
      </aside>
    </>
  );
}
