// apps/finance/src/lib/components/ForecastHubView.svelte
<script>
  // Port of src/components/ForecastHubView.tsx.
  import { t } from '$lib/i18n.svelte.js'
  import HorizontalTabs from './HorizontalTabs.svelte'
  import TabPanel from './TabPanel.svelte'
  import ForecastView from './ForecastView.svelte'
  import ScenariosView from './ScenariosView.svelte'

  /** @typedef {'forecast' | 'scenarios'} ForecastSection */

  /** @type {{
   *   data: import('../../types.js').FinanceData,
   *   projection: ReturnType<typeof import('$lib/projection.js').computeProjection>,
   *   displayLiquidCash?: number,
   *   cashAnchors?: import('../../engine/reconciliation.js').LiquidCashAnchors,
   *   onGoTab?: (tab: string, section?: string) => void,
   *   active: ForecastSection,
   *   onChange: (section: ForecastSection) => void,
   * }} */
  let { data, projection, displayLiquidCash, cashAnchors, onGoTab, active, onChange } = $props()

  const sections = $derived([
    { id: /** @type {ForecastSection} */ ('forecast'), label: t('forecastHub.sectionForecast') },
    { id: /** @type {ForecastSection} */ ('scenarios'), label: t('forecastHub.sectionScenarios') },
  ])
</script>

<div class="grid gap-6">
  <HorizontalTabs
    items={sections}
    activeId={active}
    onChange={(id) => onChange(/** @type {ForecastSection} */ (id))}
    ariaLabel={t('forecastHub.sectionAria')}
  >
    <TabPanel tabId="forecast" active={active === 'forecast'}>
      <ForecastView {data} {projection} {displayLiquidCash} {cashAnchors} {onGoTab} />
    </TabPanel>
    <TabPanel tabId="scenarios" active={active === 'scenarios'}>
      <ScenariosView />
    </TabPanel>
  </HorizontalTabs>
</div>

// apps/finance/src/components/ForecastHubView.tsx
import type { FinanceData } from "../types";
import { useLocale } from "../i18n/context";
import type { Projection } from "../hooks/useProjection";
import type { LiquidCashAnchors } from "../engine/reconciliation";
import type { GoTab } from "./AppShell";
import { HorizontalTabs, TabPanel } from "./HorizontalTabs";
import { ForecastView } from "./ForecastView";
import { ScenariosView } from "./ScenariosView";

export type ForecastSection = "forecast" | "scenarios";

// 「预测」：未来曲线 + 驱动它的长期场景与目标。
export function ForecastHubView({
  data,
  projection,
  displayLiquidCash,
  cashAnchors,
  onGoTab,
  active,
  onChange,
}: {
  data: FinanceData;
  projection: Projection;
  displayLiquidCash?: number;
  cashAnchors?: LiquidCashAnchors;
  onGoTab: GoTab;
  active: ForecastSection;
  onChange: (section: ForecastSection) => void;
}) {
  const { t } = useLocale();
  const sections: { id: ForecastSection; label: string }[] = [
    { id: "forecast", label: t("forecastHub.sectionForecast") },
    { id: "scenarios", label: t("forecastHub.sectionScenarios") },
  ];

  return (
    <div className="grid gap-6">
      <HorizontalTabs
        items={sections}
        activeId={active}
        onChange={onChange}
        ariaLabel={t("forecastHub.sectionAria")}
      >
        <TabPanel tabId="forecast" active={active === "forecast"}>
          <ForecastView
            data={data}
            projection={projection}
            displayLiquidCash={displayLiquidCash}
            cashAnchors={cashAnchors}
            onGoTab={onGoTab}
          />
        </TabPanel>
        <TabPanel tabId="scenarios" active={active === "scenarios"}>
          <ScenariosView />
        </TabPanel>
      </HorizontalTabs>
    </div>
  );
}
