// apps/finance/src/lib/components/LedgerProductStrip.svelte
<script>
  // 端口自 src/components/LedgerProductStrip.tsx。
  import { t } from '$lib/i18n.svelte.js'
  import { moneyPrecise } from '$lib/format.js'
  import { lineItemImageSrc, uniqueLineItems } from '$lib/engine/purchaseEnrichment'

  const DEFAULT_MAX = 3

  let { enrichment, privacy, maxItems = DEFAULT_MAX } = $props()

  const items = $derived(uniqueLineItems(enrichment.lineItems))
  const shown = $derived(items.slice(0, maxItems))
  const extra = $derived(items.length - shown.length)
</script>

{#if items.length > 0}
  <ul class="ledger-product-strip" aria-label={t('history.ledgerProductsAria')}>
    {#each shown as item (item.asin || item.detailUrl || item.title)}
      {@const imgSrc = lineItemImageSrc(item)}
      <li class="ledger-product-chip">
        {#if imgSrc && !privacy}
          <img
            class="ledger-product-chip-img"
            src={imgSrc}
            alt=""
            loading="lazy"
            decoding="async"
            referrerpolicy="no-referrer"
          />
        {/if}
        <span class="ledger-product-chip-text">
          {#if item.detailUrl}
            <a href={item.detailUrl} target="_blank" rel="noopener noreferrer">{item.title}</a>
          {:else}
            {item.title}
          {/if}
          {#if (item.quantity ?? 1) > 1}
            <span class="ledger-product-chip-qty"> ×{item.quantity}</span>
          {/if}
          {#if item.price != null}
            <span class="ledger-product-chip-price"> {moneyPrecise(item.price, privacy)}</span>
          {/if}
        </span>
      </li>
    {/each}
    {#if extra > 0}
      <li class="ledger-product-chip ledger-product-chip--more">
        {t('history.ledgerProductsMore', { count: extra })}
      </li>
    {/if}
  </ul>
{/if}

// apps/finance/src/components/LedgerProductStrip.tsx
import { useLocale } from '../i18n/context'
import { moneyPrecise } from '../format'
import type { PurchaseEnrichment } from '../engine/purchaseEnrichment'
import { lineItemImageSrc, uniqueLineItems } from '../engine/purchaseEnrichment'

const DEFAULT_MAX = 3

export function LedgerProductStrip({
  enrichment,
  privacy,
  maxItems = DEFAULT_MAX,
}: {
  enrichment: PurchaseEnrichment
  privacy: boolean
  maxItems?: number
}) {
  const { t: tl } = useLocale()
  const items = uniqueLineItems(enrichment.lineItems)
  if (items.length === 0) return null

  const shown = items.slice(0, maxItems)
  const extra = items.length - shown.length

  return (
    <ul
      className="ledger-product-strip"
      aria-label={tl('history.ledgerProductsAria')}
    >
      {shown.map((item) => {
        const imgSrc = lineItemImageSrc(item)
        return (
          <li
            className="ledger-product-chip"
            key={item.asin || item.detailUrl || item.title}
          >
            {imgSrc && !privacy && (
              <img
                className="ledger-product-chip-img"
                src={imgSrc}
                alt=""
                loading="lazy"
                decoding="async"
                referrerPolicy="no-referrer"
              />
            )}
            <span className="ledger-product-chip-text">
              {item.detailUrl ? (
                <a
                  href={item.detailUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {item.title}
                </a>
              ) : (
                item.title
              )}
              {(item.quantity ?? 1) > 1 && (
                <span className="ledger-product-chip-qty">
                  {' '}
                  ×{item.quantity}
                </span>
              )}
              {item.price != null && (
                <span className="ledger-product-chip-price">
                  {' '}
                  {moneyPrecise(item.price, privacy)}
                </span>
              )}
            </span>
          </li>
        )
      })}
      {extra > 0 && (
        <li className="ledger-product-chip ledger-product-chip--more">
          {tl('history.ledgerProductsMore', { count: extra })}
        </li>
      )}
    </ul>
  )
}
