// apps/finance/src/lib/components/RecordsView.svelte
<script>
  // Port of src/components/RecordsView.tsx.
  import { t } from '$lib/i18n.svelte.js'
  import HorizontalTabs from './HorizontalTabs.svelte'
  import TabPanel from './TabPanel.svelte'
  import HistoryView from './HistoryView.svelte'
  import CashFlowsView from './CashFlowsView.svelte'
  import FutureCashflowView from './FutureCashflowView.svelte'

  /** @typedef {'insights' | 'fixed' | 'oneoff'} RecordsSection */

  /** @type {{
   *   data: import('../../types.js').FinanceData,
   *   active: RecordsSection,
   *   onChange: (section: RecordsSection) => void,
   *   onGoTab?: (tab: string, section?: string, opts?: { ledgerSearch?: string, focusEventId?: string }) => void,
   *   ledgerSearch?: string,
   *   onLedgerSearchConsumed?: () => void,
   *   focusEventId?: string,
   *   onFocusEventConsumed?: () => void,
   *   onQuickAdd?: () => void,
   * }} */
  let {
    data,
    active,
    onChange,
    onGoTab,
    ledgerSearch,
    onLedgerSearchConsumed,
    focusEventId,
    onFocusEventConsumed,
    onQuickAdd,
  } = $props()

  const sections = $derived([
    { id: 'insights', label: t('records.sectionInsights') },
    { id: 'fixed', label: t('records.sectionFixed') },
    { id: 'oneoff', label: t('records.sectionOneoff') },
  ])
</script>

<div class="records-view">
  <HorizontalTabs
    items={sections}
    activeId={active}
    onChange={(id) => onChange(/** @type {RecordsSection} */ (id))}
    ariaLabel={t('records.sectionAria')}
  >
    <TabPanel tabId="insights" active={active === 'insights'} class="records-panel">
      <HistoryView
        {data}
        initialLedgerSearch={ledgerSearch}
        {onLedgerSearchConsumed}
        {onQuickAdd}
      />
    </TabPanel>
    <TabPanel tabId="fixed" active={active === 'fixed'} class="records-panel">
      <CashFlowsView />
    </TabPanel>
    <TabPanel tabId="oneoff" active={active === 'oneoff'} class="records-panel">
      <FutureCashflowView {onGoTab} {focusEventId} onFocusConsumed={onFocusEventConsumed} />
    </TabPanel>
  </HorizontalTabs>
</div>

// apps/finance/src/components/RecordsView.tsx
import type { FinanceData } from "../types";
import { useLocale } from "../i18n/context";
import type { GoTab } from "./AppShell";
import { HorizontalTabs, TabPanel } from "./HorizontalTabs";
import { HistoryView } from "./HistoryView";
import { CashFlowsView } from "./CashFlowsView";
import { FutureCashflowView } from "./FutureCashflowView";

export type RecordsSection = "insights" | "fixed" | "oneoff";

// 「记录」：真实交易洞察 + 固定收支 + 大额收支登记。
export function RecordsView({
  data,
  active,
  onChange,
  onGoTab,
  ledgerSearch,
  onLedgerSearchConsumed,
  focusEventId,
  onFocusEventConsumed,
  onQuickAdd,
}: {
  data: FinanceData;
  active: RecordsSection;
  onChange: (section: RecordsSection) => void;
  onGoTab?: GoTab;
  ledgerSearch?: string;
  onLedgerSearchConsumed?: () => void;
  focusEventId?: string;
  onFocusEventConsumed?: () => void;
  onQuickAdd?: () => void;
}) {
  const { t } = useLocale();
  const sections: { id: RecordsSection; label: string }[] = [
    { id: "insights", label: t("records.sectionInsights") },
    { id: "fixed", label: t("records.sectionFixed") },
    { id: "oneoff", label: t("records.sectionOneoff") },
  ];

  return (
    <div className="records-view">
      <HorizontalTabs
        items={sections}
        activeId={active}
        onChange={onChange}
        ariaLabel={t("records.sectionAria")}
      >
        <TabPanel tabId="insights" active={active === "insights"} className="records-panel">
          <HistoryView
            data={data}
            initialLedgerSearch={ledgerSearch}
            onLedgerSearchConsumed={onLedgerSearchConsumed}
            onQuickAdd={onQuickAdd}
          />
        </TabPanel>
        <TabPanel tabId="fixed" active={active === "fixed"} className="records-panel">
          <CashFlowsView />
        </TabPanel>
        <TabPanel tabId="oneoff" active={active === "oneoff"} className="records-panel">
          <FutureCashflowView
            onGoTab={onGoTab}
            focusEventId={focusEventId}
            onFocusConsumed={onFocusEventConsumed}
          />
        </TabPanel>
      </HorizontalTabs>
    </div>
  );
}
