// apps/finance/src/components/BrandMark.tsx
import { useThemePreference } from '../hooks/useThemePreference'

type BrandMarkProps = {
  size?: number
  className?: string
}

const CIRCLE_96 = {
  light: '/assets/brand/brand-circle-light-96.png',
  dark: '/assets/brand/brand-circle-dark-96.png',
} as const

const CIRCLE_48 = {
  light: '/assets/brand/brand-circle-light-48.png',
  dark: '/assets/brand/brand-circle-dark-48.png',
} as const

export function BrandMark({ size = 28, className = '' }: BrandMarkProps) {
  const [, , resolved] = useThemePreference()
  const src = resolved === 'dark' ? CIRCLE_96.dark : CIRCLE_96.light
  const srcSet =
    resolved === 'dark'
      ? `${CIRCLE_48.dark} 1x, ${CIRCLE_96.dark} 2x`
      : `${CIRCLE_48.light} 1x, ${CIRCLE_96.light} 2x`

  return (
    <img
      src={src}
      srcSet={srcSet}
      alt=""
      aria-hidden
      className={className}
      width={size}
      height={size}
    />
  )
}

// packages/platform-web/src/svelte/brand/BrandMark.svelte
<script>
  /** @type {{ size?: number, class?: string, lightSrc?: string, darkSrc?: string, lightSrcSet?: string, darkSrcSet?: string }} */
  let {
    size = 28,
    class: className = '',
    lightSrc = '/brand-circle-light-96.png',
    darkSrc = '/brand-circle-dark-96.png',
    lightSrcSet = '/brand-circle-light-48.png 1x, /brand-circle-light-96.png 2x',
    darkSrcSet = '/brand-circle-dark-48.png 1x, /brand-circle-dark-96.png 2x',
  } = $props();
</script>

<span
  class="brand-icon-pair {className}"
  style="--brand-icon-size: {size}px"
  aria-hidden="true"
>
  <img
    src={lightSrc}
    srcset={lightSrcSet}
    alt=""
    class="brand-icon-light"
    width={size}
    height={size}
  />
  <img
    src={darkSrc}
    srcset={darkSrcSet}
    alt=""
    class="brand-icon-dark"
    width={size}
    height={size}
  />
</span>
