// apps/finance/src/lib/components/settings/SettingsPrefRow.svelte
<script>
  /** @type {{ label: string, desc?: string, children?: import('svelte').Snippet }} */
  let { label, desc, children } = $props()
</script>

<div class="pref-row">
  <div class="pref-copy">
    <div class="pref-label">{label}</div>
    {#if desc}
      <p class="pref-desc">{desc}</p>
    {/if}
  </div>
  <div class="pref-control">
    {@render children?.()}
  </div>
</div>

// apps/finance/src/components/settings/SettingsPrefRow.tsx
import type { ReactNode } from "react";

export function SettingsPrefRow({
  label,
  desc,
  children,
}: {
  label: string;
  desc?: string;
  children: ReactNode;
}) {
  return (
    <div className="pref-row">
      <div className="pref-copy">
        <div className="pref-label">{label}</div>
        {desc ? <p className="pref-desc">{desc}</p> : null}
      </div>
      <div className="pref-control">{children}</div>
    </div>
  );
}
