// apps/finance/src/lib/components/stocks/LiveStatusBar.svelte
<script>
  // Port of LiveStatusBar from src/components/stocks/LiveStatusBar.tsx.
  import { t, intlLocaleTag } from '$lib/i18n.svelte.js'

  /** @typedef {'idle' | 'loading' | 'live' | 'partial' | 'stale' | 'error' | 'paused'} LiveTrackStatus */

  /** @type {{ status: LiveTrackStatus, updatedAt: string | null, pollIntervalSec: number, error: string | null }} */
  let { status, updatedAt, pollIntervalSec, error } = $props()

  const STATUS_DOT = {
    idle: 'dot',
    loading: 'dot warn',
    live: 'dot ok',
    partial: 'dot warn',
    stale: 'dot warn',
    error: 'dot critical',
    paused: 'dot',
  }

  const timeLabel = $derived(
    updatedAt
      ? new Date(updatedAt).toLocaleTimeString(intlLocaleTag(), {
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
        })
      : '--',
  )
</script>

<div class="stocks-live-status">
  <span class={STATUS_DOT[status]} aria-hidden="true"></span>
  <span>
    {t('stocks.liveStatus.barTemplate', {
      status: t(`stocks.liveStatus.${status}`),
      time: timeLabel,
      interval: pollIntervalSec,
    })}
  </span>
  {#if error && status !== 'live'}
    <span class="stocks-live-status-note">{error}</span>
  {/if}
</div>

// apps/finance/src/components/stocks/LiveStatusBar.tsx
import type { LiveTrackStatus } from "../../hooks/useHoldingsLive";
import { useLocale } from "../../i18n/context";

const STATUS_DOT: Record<LiveTrackStatus, string> = {
  idle: "dot",
  loading: "dot warn",
  live: "dot ok",
  partial: "dot warn",
  stale: "dot warn",
  error: "dot critical",
  paused: "dot",
};

export function LiveStatusBar({
  status,
  updatedAt,
  pollIntervalSec,
  error,
}: {
  status: LiveTrackStatus;
  updatedAt: string | null;
  pollIntervalSec: number;
  error: string | null;
}) {
  const { t, intlLocale } = useLocale();
  const timeLabel = updatedAt
    ? new Date(updatedAt).toLocaleTimeString(intlLocale, {
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit",
      })
    : "--";

  return (
    <div className="stocks-live-status">
      <span className={STATUS_DOT[status]} aria-hidden />
      <span>
        {t("stocks.liveStatus.barTemplate", {
          status: t(`stocks.liveStatus.${status}`),
          time: timeLabel,
          interval: pollIntervalSec,
        })}
      </span>
      {error && status !== "live" && (
        <span className="stocks-live-status-note">{error}</span>
      )}
    </div>
  );
}
